package com.jarol.auth.auth_api.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    USER_DISABLED,
    USER_NOT_VERIFIED,
    USER_ALREADY_VERIFIED,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    ROLE_NOT_FOUND,
    SESSION_NOT_FOUND,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    INVALID_PARAMETERS,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    TOKEN_NOT_FOUND,
    ACCESS_DENIED,
    TOO_MANY_REQUESTS,
    ACCOUNT_LOCKED
}
